name: tcr-status-led 
base: core20 
version: '0.1'
summary: controls the status LED on the Microfabricator # 79 char long summary
description: |
  This program controls the status LED on the Microfabricator

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  status-led:
    command: bin/mfab-status-led
    daemon: simple # Ref: https://askubuntu.com/questions/784489/how-do-system-services-work-in-snaps
    plugs: [gpio]

parts:
  rpi-status-led:
    plugin: rust
    source: ./
